#!/bin/bash
csv_file="/opt/User.csv"
while IFS=";" read -r firstName role phone ou street zip city country password; do
	if [ "$FirstName" == "First Name" ]; then
		continue
	fi
	username="${firstName,,}.${lastName,,}"
	sudo-samba-tool user add "$username" P@ssw0rd
done < "$csv_file"
